{% set version = "0.1.3" %}
{% set sha256 = "9831f53ed6c564b59d72a047e627785139069e4bc0311d3393fd9fc6f52389bb" %}

package:
  name: ipyurl
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/ipyurl/ipyurl-{{ version }}.tar.gz
  sha256: 080854c36a478487633fdeeae7552e8269b11b1f97f7971f433375f5faa55908

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - nodejs
    - yarn
    - jupyterlab =3
    - jupyter-packaging
  run:
    - python >={{ python_min }}
    - ipywidgets >=7.0.0,<8.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - ipyurl
  commands:
    - test -f ${PREFIX}/share/jupyter/nbextensions/ipyurl/extension.js                             # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/ipyurl/index.js                                 # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/ipyurl/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\ipyurl\\extension.js (exit 1)           # [win]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\ipyurl\\index.js (exit 1)               # [win]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\ipyurl\\package.json (exit 1)          # [win]

about:
  home: https://github.com/davidbrochart/ipyurl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A Jupyter Widget Library for accessing the server's URL
  doc_url: https://github.com/davidbrochart/ipyurl
  dev_url: https://github.com/davidbrochart/ipyurl

extra:
  recipe-maintainers:
    - davidbrochart
